### ISSUE TITLE
 When will your dataset be available?

### ISSUE THREAD

**Issue by chihina** [PKU-ICST-MIPL/FineSports_CVPR2024#1]
Hi!

I'm really interesting in this work.
When will your dataset be avaliable?

Thanks.

**Comment by PKU-ICST-MIPL** [comment]
Thank you for your interest in our work. We are currently organizing the dataset and annotation files, and the dataset will be available soon.

**Comment by PKU-ICST-MIPL** [comment]
> Hi!
> 
> I'm really interesting in this work. When will your dataset be avaliable?
> 
> Thanks.

Thank you for your interest in our work. We are currently organizing the dataset and annotation files, and the dataset will be available soon.

**Comment by chihina** [comment]
I appreciate your response. Thank you!

**Comment by LightingMc** [comment]
Any updates?

**Comment by Ironieser** [comment]
Any updates?

**Comment by YangYangGirl** [comment]
Hi!

I'm also really interesting in this work.
When will your dataset be avaliable?

Thanks.

**Comment by emma-sjwang** [comment]
Any updates?
